/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProductosIndexRouteImport } from './routes/_authenticated/productos/index'
import { Route as AuthenticatedCategoriasIndexRouteImport } from './routes/_authenticated/categorias/index'
import { Route as AuthenticatedProductosNuevoRouteImport } from './routes/_authenticated/productos/nuevo'
import { Route as AuthenticatedProductosProductIdRouteImport } from './routes/_authenticated/productos/$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductosIndexRoute =
  AuthenticatedProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriasIndexRoute =
  AuthenticatedCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosNuevoRoute =
  AuthenticatedProductosNuevoRouteImport.update({
    id: '/productos/nuevo',
    path: '/productos/nuevo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosProductIdRoute =
  AuthenticatedProductosProductIdRouteImport.update({
    id: '/productos/$productId',
    path: '/productos/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/productos/$productId': typeof AuthenticatedProductosProductIdRoute
  '/productos/nuevo': typeof AuthenticatedProductosNuevoRoute
  '/categorias/': typeof AuthenticatedCategoriasIndexRoute
  '/productos/': typeof AuthenticatedProductosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/productos/$productId': typeof AuthenticatedProductosProductIdRoute
  '/productos/nuevo': typeof AuthenticatedProductosNuevoRoute
  '/categorias': typeof AuthenticatedCategoriasIndexRoute
  '/productos': typeof AuthenticatedProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/productos/$productId': typeof AuthenticatedProductosProductIdRoute
  '/_authenticated/productos/nuevo': typeof AuthenticatedProductosNuevoRoute
  '/_authenticated/categorias/': typeof AuthenticatedCategoriasIndexRoute
  '/_authenticated/productos/': typeof AuthenticatedProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/productos/$productId'
    | '/productos/nuevo'
    | '/categorias/'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/productos/$productId'
    | '/productos/nuevo'
    | '/categorias'
    | '/productos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/productos/$productId'
    | '/_authenticated/productos/nuevo'
    | '/_authenticated/categorias/'
    | '/_authenticated/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/': {
      id: '/_authenticated/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof AuthenticatedProductosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias/': {
      id: '/_authenticated/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof AuthenticatedCategoriasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/nuevo': {
      id: '/_authenticated/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/productos/nuevo'
      preLoaderRoute: typeof AuthenticatedProductosNuevoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/$productId': {
      id: '/_authenticated/productos/$productId'
      path: '/productos/$productId'
      fullPath: '/productos/$productId'
      preLoaderRoute: typeof AuthenticatedProductosProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProductosProductIdRoute: typeof AuthenticatedProductosProductIdRoute
  AuthenticatedProductosNuevoRoute: typeof AuthenticatedProductosNuevoRoute
  AuthenticatedCategoriasIndexRoute: typeof AuthenticatedCategoriasIndexRoute
  AuthenticatedProductosIndexRoute: typeof AuthenticatedProductosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProductosProductIdRoute: AuthenticatedProductosProductIdRoute,
  AuthenticatedProductosNuevoRoute: AuthenticatedProductosNuevoRoute,
  AuthenticatedCategoriasIndexRoute: AuthenticatedCategoriasIndexRoute,
  AuthenticatedProductosIndexRoute: AuthenticatedProductosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
