/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosIndexRouteImport } from './routes/_authenticated/usuarios/index'
import { Route as AuthenticatedResenasIndexRouteImport } from './routes/_authenticated/resenas/index'
import { Route as AuthenticatedProductosIndexRouteImport } from './routes/_authenticated/productos/index'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos/index'
import { Route as AuthenticatedCategoriasIndexRouteImport } from './routes/_authenticated/categorias/index'
import { Route as AuthenticatedProductosNuevoRouteImport } from './routes/_authenticated/productos/nuevo'
import { Route as AuthenticatedProductosProductIdRouteImport } from './routes/_authenticated/productos/$productId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsuariosIndexRoute =
  AuthenticatedUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResenasIndexRoute =
  AuthenticatedResenasIndexRouteImport.update({
    id: '/resenas/',
    path: '/resenas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosIndexRoute =
  AuthenticatedProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriasIndexRoute =
  AuthenticatedCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosNuevoRoute =
  AuthenticatedProductosNuevoRouteImport.update({
    id: '/productos/nuevo',
    path: '/productos/nuevo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductosProductIdRoute =
  AuthenticatedProductosProductIdRouteImport.update({
    id: '/productos/$productId',
    path: '/productos/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/productos/$productId': typeof AuthenticatedProductosProductIdRoute
  '/productos/nuevo': typeof AuthenticatedProductosNuevoRoute
  '/categorias/': typeof AuthenticatedCategoriasIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/productos/': typeof AuthenticatedProductosIndexRoute
  '/resenas/': typeof AuthenticatedResenasIndexRoute
  '/usuarios/': typeof AuthenticatedUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/productos/$productId': typeof AuthenticatedProductosProductIdRoute
  '/productos/nuevo': typeof AuthenticatedProductosNuevoRoute
  '/categorias': typeof AuthenticatedCategoriasIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/productos': typeof AuthenticatedProductosIndexRoute
  '/resenas': typeof AuthenticatedResenasIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/productos/$productId': typeof AuthenticatedProductosProductIdRoute
  '/_authenticated/productos/nuevo': typeof AuthenticatedProductosNuevoRoute
  '/_authenticated/categorias/': typeof AuthenticatedCategoriasIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/productos/': typeof AuthenticatedProductosIndexRoute
  '/_authenticated/resenas/': typeof AuthenticatedResenasIndexRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/productos/$productId'
    | '/productos/nuevo'
    | '/categorias/'
    | '/pedidos/'
    | '/productos/'
    | '/resenas/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/'
    | '/productos/$productId'
    | '/productos/nuevo'
    | '/categorias'
    | '/pedidos'
    | '/productos'
    | '/resenas'
    | '/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/'
    | '/_authenticated/productos/$productId'
    | '/_authenticated/productos/nuevo'
    | '/_authenticated/categorias/'
    | '/_authenticated/pedidos/'
    | '/_authenticated/productos/'
    | '/_authenticated/resenas/'
    | '/_authenticated/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resenas/': {
      id: '/_authenticated/resenas/'
      path: '/resenas'
      fullPath: '/resenas/'
      preLoaderRoute: typeof AuthenticatedResenasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/': {
      id: '/_authenticated/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof AuthenticatedProductosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias/': {
      id: '/_authenticated/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof AuthenticatedCategoriasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/nuevo': {
      id: '/_authenticated/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/productos/nuevo'
      preLoaderRoute: typeof AuthenticatedProductosNuevoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productos/$productId': {
      id: '/_authenticated/productos/$productId'
      path: '/productos/$productId'
      fullPath: '/productos/$productId'
      preLoaderRoute: typeof AuthenticatedProductosProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProductosProductIdRoute: typeof AuthenticatedProductosProductIdRoute
  AuthenticatedProductosNuevoRoute: typeof AuthenticatedProductosNuevoRoute
  AuthenticatedCategoriasIndexRoute: typeof AuthenticatedCategoriasIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedProductosIndexRoute: typeof AuthenticatedProductosIndexRoute
  AuthenticatedResenasIndexRoute: typeof AuthenticatedResenasIndexRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProductosProductIdRoute: AuthenticatedProductosProductIdRoute,
  AuthenticatedProductosNuevoRoute: AuthenticatedProductosNuevoRoute,
  AuthenticatedCategoriasIndexRoute: AuthenticatedCategoriasIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedProductosIndexRoute: AuthenticatedProductosIndexRoute,
  AuthenticatedResenasIndexRoute: AuthenticatedResenasIndexRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
